from langchain.prompts import PromptTemplate

template = """Find 5 sentences from the text that contribute the most to the classification of this document as [Strategy]
===========
2 reports.weforum.org/global-risks-2017/part-1-global-risks-2017/ and nature.com/articles/nature21359 3 Connect: How Companies Succeed by Engaging Radically with Society, McKinsey 2015.A new role for business A changing world brings changing e xpectations for business, adding up to a new role for the private sector in general and large businesses in particular. This is evident in the United Nations’ Sustainable Development Goals (SDGs), which express the global community’s most important priorities for the future. They also express what is increasingly expected of businesses: T o work in partnerships to create solutions that contribute to developing a more sustainable and inclusive world.
Such deep engagement and collaboration also drive business value. There is growing evidence that engagement will drive both sustainable development and corporate performance, becoming a new frontier in competitive advantage.3 How we engage for change A.P . Moller - Maersk has pursued such eng agement for some time. In 2009, we took on a leadership role in the shipping industry to reduce CO2 emissions, and pushed to get the issue of climate change high on the industry’s agenda. We continued this work in line with our 2014 sustainability strategy, which was based on the idea of looking for touchpoints where our business can positively impact sustainable development and at the same time create business value. This has been true for our work on trade and climate change (read more on pages 10 and 14). We were instrumental in establishing the Maritime Anti-Corruption Network (MACN) in 2011, which set the tone for a partnership-based model for combating corruption and facilitation payments in ports. We are currently developing a blueprint for collaboration between foreign service representations and companies in the battle against facilitation payments (read more on page 38).
In 2016, we began working to change the ship recycling industry to raise standards and create safe working conditions and environmentally sound practices at shipbreaking facilities in Alang, India. Working in partnership with participating yards, the on-the-ground achievements have the potential to break the gridlock in the ship recycling industry. We are now working to accelerate change through a push for increased transparency on shipowners’ policies and practices (read more on page 42).We also see that resource scarcity
– lack of water, food products and natural minerals for example – is no longer a far-off risk, but a reality in some parts of the world, and will affect more and more people and businesses within the next 10 – 15 years.2 Finally, digitisation is about to disrupt our industry and significantly change the landscape in which we operate. We are taking steps to adapt our company to this changing world. Our vision is to become a global integrator of container logistics through digital innovation, connecting and simplifying the global supply chain. This includes providing simple solutions to our customers’ complex supply chain needs, elevating the customer experience and extending the industry’s most effective and efficient delivery network to every market in the world. We want to make the shipping of containerised goods as easy for our customers as it is to send a package from A to B today. Alongside this, we will be finding viable solutions for our activities in the energy sector.SUSTAINABLE DEVEL OPMENT GOALS The United Nations’ Sus tainable Development Goals (SDGs) express the most important issues that the global community has identified as future priorities. Our business touches, directly or indirectly, on all 17 SDGs. We have selected five SDGs where we can have the greatest positive impact, and where we intend to track our progress: Sustainability Report 201 709 INTRODUC TION A CHANGING WORLD RESPONSIBLE BUSINESS PRACTICES ASSURANCE AND PERFORMANCE DA T A
===========
This is evident in the United Nations’ Sustainable Development Goals (SDGs), which express the global community’s most important priorities for the future.\nWe were instrumental in establishing the Maritime Anti-Corruption Network (MACN) in 2011, which set the tone for a partnership-based model for combating corruption and facilitation payments in ports.\nWe are taking steps to adapt our company to this changing world. Our vision is to become a global integrator of container logistics through digital innovation, connecting and simplifying the global supply chain.\nOur business touches, directly or indirectly, on all 17 SDGs. We have selected five SDGs where we can have the greatest positive impact, and where we intend to track our progress:\nThis report also represents our statutory statement on social responsibility and underrepresented gender in accordance with sections §99a & b of the Danish Financial Statements Act.

----------

Find 5 sentences from the text that contribute the most to the classification of this document as [{disclosure}]
===========
{summaries}
===========
[ANSWER]:
"""

STUFF_PROMPT = PromptTemplate(
    template=template, input_variables=["summaries", "disclosure"]
)
